// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCav-SpO5sropao7GFlIGctnStpiWxW624',
    appId: '1:98815801026:web:4add813b32ffd8721b6d5b',
    messagingSenderId: '98815801026',
    projectId: 'finance-tracker-app-13893',
    authDomain: 'finance-tracker-app-13893.firebaseapp.com',
    storageBucket: 'finance-tracker-app-13893.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPkeIRg6gkgBxIISRlEL1rfawzslDHQGU',
    appId: '1:98815801026:android:d5d5b9af489058141b6d5b',
    messagingSenderId: '98815801026',
    projectId: 'finance-tracker-app-13893',
    storageBucket: 'finance-tracker-app-13893.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApkMWCXR3Wj8DhgxJJjZoCuXTA2rg77Fs',
    appId: '1:98815801026:ios:519d28d4eaf368e31b6d5b',
    messagingSenderId: '98815801026',
    projectId: 'finance-tracker-app-13893',
    storageBucket: 'finance-tracker-app-13893.firebasestorage.app',
    iosBundleId: 'com.example.personalFinanceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApkMWCXR3Wj8DhgxJJjZoCuXTA2rg77Fs',
    appId: '1:98815801026:ios:519d28d4eaf368e31b6d5b',
    messagingSenderId: '98815801026',
    projectId: 'finance-tracker-app-13893',
    storageBucket: 'finance-tracker-app-13893.firebasestorage.app',
    iosBundleId: 'com.example.personalFinanceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCav-SpO5sropao7GFlIGctnStpiWxW624',
    appId: '1:98815801026:web:3ebcd19fb58eb68c1b6d5b',
    messagingSenderId: '98815801026',
    projectId: 'finance-tracker-app-13893',
    authDomain: 'finance-tracker-app-13893.firebaseapp.com',
    storageBucket: 'finance-tracker-app-13893.firebasestorage.app',
  );
}
